repo = "helix-editor/helix"

remote-branch = "master"

local-branch = "patchy"

pull-requests = [
  "7783", # horizontal picker preview
  "12369", # icons v2 (merge conflict with 13666)
  # "13666", # status element styling (merge conflict with 12369)
  # "13197", # welcome screen
  # "12806", # path in file picker (refer to my branch)
  # "11497", # rounded corners (refer to my branch)
  "13318", # allow themeing the status bar
  "12944", # ":left" ":center" and ":right" (didnt actually use it)
  "14118", # rainbow indent guides
  "14072", # scroll bufferline (conflict)

  # "13206", # word completion (merged)
  # "13627", # better file sizes (merged)
  # "13530", # rainbow brackets (merged)

  # "6118", # sticky context
  # "11790", # move buffers in the bufferline (conflict)
  # "12151", # allow themeing the items in completion (merge conflict)
  # "13306", # add custom icon for color swatches (merge conflict)
  # "12520", # Picker titles (merge conflict)

  # "13448", # harpoon2 for helix (need to look into what it does...)

  # "8675", # steel plugin system [patched chaotically]
  "14876", # inline text completion
]

patches = []
